[
  {
    ids: ["analysis_1757086993_JUPyiwrY", "analysis_1757087043_JUPyiwrY"],
    embeddings: None,
    metadatas: [
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-05",
        analysis_id:
          "security_1757094193_JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "security_only",
        analysis_year: "2025",
        confidence_score: 90.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1757086993_JUPyiwrY",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 886720,
        liquidity: 0.0,
        lp_status: "locked",
        market_cap: 3403619484.42,
        mint_authority_active: False,
        overall_score: 70.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 0.969,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 3,
        sniper_risk: "unknown",
        source_event: "webhook_mint",
        timestamp: "2025-09-05T17:43:14.966784",
        timestamp_unix: 1757086993,
        token_address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        token_name: "Jupiter",
        token_symbol: "JUP",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-05",
        analysis_id:
          "security_1757094243_JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "security_only",
        analysis_year: "2025",
        confidence_score: 90.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1757087043_JUPyiwrY",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 886720,
        liquidity: 0.0,
        lp_status: "locked",
        market_cap: 3403619484.42,
        mint_authority_active: False,
        overall_score: 70.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 1.074,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 3,
        sniper_risk: "unknown",
        source_event: "webhook_mint",
        timestamp: "2025-09-05T17:44:04.316052",
        timestamp_unix: 1757087043,
        token_address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        token_name: "Jupiter",
        token_symbol: "JUP",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
    ],
    documents: [
      "Token: Jupiter (JUP). Traditional security_only analysis. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 70.0. Market cap: $3,403,619,484. Perfect token distribution - no whales. Has 1 security warnings. Summary: Security checks passed. Analysis reasoning: Analysis score: 70.0/100. Security verification passed. Analysis based on 3 data sources..... Data from 3 sources. Processing time: 0.97s. Analyzed on: 2025-09-05 17:43:13.",
      "Token: Jupiter (JUP). Traditional security_only analysis. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 70.0. Market cap: $3,403,619,484. Perfect token distribution - no whales. Has 1 security warnings. Summary: Security checks passed. Analysis reasoning: Analysis score: 70.0/100. Security verification passed. Analysis based on 3 data sources..... Data from 3 sources. Processing time: 1.07s. Analyzed on: 2025-09-05 17:44:03.",
    ],
    uris: None,
    data: None,
  },
];
