[
  {
    ids: [
      "analysis_1756543228_EPjFWdd5",
      "analysis_1756543228_EPjFWdd5_1",
      "analysis_1756543228_EPjFWdd5_2",
    ],
    embeddings: None,
    metadatas: [
      {
        analysis_date: "2025-08-30",
        analysis_id: "deep_analysis_1756550428_EPjFWdd5",
        analysis_month: "2025-08",
        analysis_stopped_at_security: True,
        analysis_year: "2025",
        confidence_score: 95.0,
        content_type: "text",
        critical_issues_count: 2,
        doc_id: "analysis_1756543228_EPjFWdd5",
        doc_type: "token_analysis",
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        overall_score: 10.0,
        price_range: "unknown",
        processing_time: 1.409,
        recommendation: "avoid",
        risk_level: "critical",
        security_score: 20.0,
        security_status: "failed",
        services_successful: 3,
        source_event: "webhook_mint",
        timestamp: "2025-08-30T10:40:29.423559",
        timestamp_unix: 1756543228,
        token_address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        token_symbol: "USDC",
        volume_range: "none",
        warnings_count: 0,
      },
      {
        analysis_date: "2025-08-30",
        analysis_id: "deep_analysis_1756550428_EPjFWdd5",
        analysis_month: "2025-08",
        analysis_stopped_at_security: True,
        analysis_year: "2025",
        confidence_score: 95.0,
        content_type: "text",
        critical_issues_count: 2,
        doc_id: "analysis_1756543228_EPjFWdd5_1",
        doc_type: "token_analysis",
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        overall_score: 10.0,
        price_range: "unknown",
        processing_time: 1.409,
        recommendation: "avoid",
        risk_level: "critical",
        security_score: 20.0,
        security_status: "failed",
        services_successful: 3,
        source_event: "webhook_mint",
        timestamp: "2025-08-30T10:40:29.693299",
        timestamp_unix: 1756543228,
        token_address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        token_symbol: "USDC",
        volume_range: "none",
        warnings_count: 0,
      },
      {
        analysis_date: "2025-08-30",
        analysis_id: "deep_analysis_1756550428_EPjFWdd5",
        analysis_month: "2025-08",
        analysis_stopped_at_security: True,
        analysis_year: "2025",
        confidence_score: 95.0,
        content_type: "text",
        critical_issues_count: 2,
        doc_id: "analysis_1756543228_EPjFWdd5_2",
        doc_type: "token_analysis",
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        overall_score: 10.0,
        price_range: "unknown",
        processing_time: 1.907,
        recommendation: "avoid",
        risk_level: "critical",
        security_score: 20.0,
        security_status: "failed",
        services_successful: 3,
        source_event: "webhook_mint",
        timestamp: "2025-08-30T10:40:29.938081",
        timestamp_unix: 1756543228,
        token_address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        token_symbol: "USDC",
        volume_range: "none",
        warnings_count: 0,
      },
    ],
    documents: [
      "Token: USD Coin (USDC). Traditional deep analysis. Security status: failed. Risk level: critical. Recommendation: avoid. Overall score: 10.0. Has 2 critical security issues. Data from: goplus, rugcheck, solsniffer. Analysis source: webhook_mint. Processing time: 1.41s. Analyzed on: 2025-08-30 10:40:28.",
      "Token: USD Coin (USDC). Traditional deep analysis. Security status: failed. Risk level: critical. Recommendation: avoid. Overall score: 10.0. Has 2 critical security issues. Data from: goplus, rugcheck, solsniffer. Analysis source: webhook_mint. Processing time: 1.41s. Analyzed on: 2025-08-30 10:40:28.",
      "Token: USD Coin (USDC). Traditional deep analysis. Security status: failed. Risk level: critical. Recommendation: avoid. Overall score: 10.0. Has 2 critical security issues. Data from: goplus, rugcheck, solsniffer. Analysis source: webhook_mint. Processing time: 1.91s. Analyzed on: 2025-08-30 10:40:28.",
    ],
    uris: None,
    data: None,
  },
];
