[
  {
    ids: [
      "analysis_1756901497_4k3Dyjzv",
      "analysis_1756901576_4k3Dyjzv",
      "analysis_1756931961_4k3Dyjzv",
      "analysis_1756932025_4k3Dyjzv",
      "analysis_1756932143_4k3Dyjzv",
      "analysis_1756932252_4k3Dyjzv",
      "analysis_1756933219_4k3Dyjzv",
      "analysis_1756933788_4k3Dyjzv",
      "analysis_1756935006_4k3Dyjzv",
    ],
    embeddings: None,
    metadatas: [
      {
        ai_processing_time: 1.5011999607086182,
        ai_risk_assessment: "low",
        ai_score: 92.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id:
          "analysis_1756908697_4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "deep",
        analysis_year: "2025",
        confidence_score: 100.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756901497_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: True,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 250721,
        liquidity: 36828091.241141036,
        lp_status: "locked",
        market_cap: 1892543833.34,
        mint_authority_active: False,
        overall_score: 86.7,
        price_change_24h: 2.3636842052585685,
        price_usd: 3.470246042045996,
        processing_time: 4.861,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 7,
        sniper_risk: "low",
        source_event: "api_deep",
        timestamp: "2025-09-03T14:11:42.853513",
        timestamp_unix: 1756901497,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Raydium",
        token_symbol: "RAY",
        total_supply: 554998191.261189,
        volatility_risk: "low",
        volume_24h: 7460777.7,
        volume_liquidity_ratio: 20.258388226391403,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "low",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id:
          "analysis_1756908776_4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 100.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756901576_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 250721,
        liquidity: 36839032.47658041,
        lp_status: "locked",
        market_cap: 1892543833.34,
        mint_authority_active: False,
        overall_score: 83.1,
        price_change_24h: 1.987117629393633,
        price_usd: 3.459907735882926,
        processing_time: 3.657,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 7,
        sniper_risk: "low",
        source_event: "api_quick",
        timestamp: "2025-09-03T14:13:00.356631",
        timestamp_unix: 1756901576,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Raydium",
        token_symbol: "RAY",
        total_supply: 554998191.261189,
        volatility_risk: "low",
        volume_24h: 7472328.42,
        volume_liquidity_ratio: 20.28372603094385,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "low",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id:
          "analysis_1756939161_4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 100.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756931961_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 250721,
        liquidity: 36580705.04222895,
        lp_status: "locked",
        market_cap: 1898093813.8,
        mint_authority_active: False,
        overall_score: 83.1,
        price_change_24h: -0.3975419281297689,
        price_usd: 3.430591067926669,
        processing_time: 9.876,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 7,
        sniper_risk: "low",
        source_event: "api_quick",
        timestamp: "2025-09-03T22:39:31.962192",
        timestamp_unix: 1756931961,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Raydium",
        token_symbol: "RAY",
        total_supply: 554998191.170867,
        volatility_risk: "low",
        volume_24h: 6844909.36,
        volume_liquidity_ratio: 18.711802717028558,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "low",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id: "analysis_pump_1756939225_4k3Dyjzv",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 0.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756932025_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: False,
        has_rugcheck: False,
        has_solsniffer: False,
        holder_count: 0,
        liquidity: 0.0,
        lp_status: "unknown",
        market_cap: 0.0,
        mint_authority_active: False,
        overall_score: 0.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 0.0,
        recommendation: "HOLD",
        risk_level: "unknown",
        security_score: 100,
        security_status: "unsafe",
        services_successful: 0,
        sniper_risk: "unknown",
        source_event: "unknown",
        timestamp: "2025-09-03T22:40:25.354098",
        timestamp_unix: 1756932025,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Unknown Token",
        token_symbol: "N/A",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 0,
        warnings_list: "[]",
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id: "analysis_pump_1756939343_4k3Dyjzv",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 0.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756932143_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: False,
        has_rugcheck: False,
        has_solsniffer: False,
        holder_count: 0,
        liquidity: 0.0,
        lp_status: "unknown",
        market_cap: 0.0,
        mint_authority_active: False,
        overall_score: 0.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 0.0,
        recommendation: "HOLD",
        risk_level: "unknown",
        security_score: 100,
        security_status: "unsafe",
        services_successful: 0,
        sniper_risk: "unknown",
        source_event: "unknown",
        timestamp: "2025-09-03T22:42:23.868278",
        timestamp_unix: 1756932143,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Unknown Token",
        token_symbol: "N/A",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 0,
        warnings_list: "[]",
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id: "analysis_pump_1756939452_4k3Dyjzv",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 0.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756932252_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: False,
        has_rugcheck: False,
        has_solsniffer: False,
        holder_count: 0,
        liquidity: 0.0,
        lp_status: "unknown",
        market_cap: 0.0,
        mint_authority_active: False,
        overall_score: 0.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 0.0,
        recommendation: "HOLD",
        risk_level: "unknown",
        security_score: 100,
        security_status: "unsafe",
        services_successful: 0,
        sniper_risk: "unknown",
        source_event: "unknown",
        timestamp: "2025-09-03T22:44:12.661143",
        timestamp_unix: 1756932252,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Unknown Token",
        token_symbol: "N/A",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 0,
        warnings_list: "[]",
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id:
          "analysis_1756940419_4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 100.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756933219_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: True,
        has_rugcheck: True,
        has_solsniffer: True,
        holder_count: 250721,
        liquidity: 36580705.04222895,
        lp_status: "locked",
        market_cap: 1898093813.8,
        mint_authority_active: False,
        overall_score: 83.1,
        price_change_24h: -0.5588407732561117,
        price_usd: 3.4292832492425873,
        processing_time: 5.406,
        recommendation: "consider",
        risk_level: "low",
        security_score: 95,
        security_status: "safe",
        services_successful: 7,
        sniper_risk: "low",
        source_event: "api_quick",
        timestamp: "2025-09-03T23:00:25.143858",
        timestamp_unix: 1756933219,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Raydium",
        token_symbol: "RAY",
        total_supply: 554998191.170867,
        volatility_risk: "low",
        volume_24h: 6858517.26,
        volume_liquidity_ratio: 18.749002382765703,
        warnings_count: 1,
        warnings_list: '["Very low liquidity detected"]',
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "low",
      },
      {
        ai_processing_time: 0.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id: "analysis_pump_1756940988_4k3Dyjzv",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "quick",
        analysis_year: "2025",
        confidence_score: 0.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756933788_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: False,
        has_rugcheck: False,
        has_solsniffer: False,
        holder_count: 0,
        liquidity: 0.0,
        lp_status: "unknown",
        market_cap: 0.0,
        mint_authority_active: False,
        overall_score: 0.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 0.0,
        recommendation: "HOLD",
        risk_level: "unknown",
        security_score: 100,
        security_status: "unsafe",
        services_successful: 0,
        sniper_risk: "unknown",
        source_event: "unknown",
        timestamp: "2025-09-03T23:09:48.230126",
        timestamp_unix: 1756933788,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Unknown Token",
        token_symbol: "N/A",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 0,
        warnings_list: "[]",
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
      {
        ai_processing_time: 1.0,
        ai_risk_assessment: "unknown",
        ai_score: 0.0,
        ai_stop_flags_count: 0,
        analysis_date: "2025-09-03",
        analysis_id: "analysis_pump_1756942206_4k3Dyjzv",
        analysis_month: "2025-09",
        analysis_stopped_at_security: False,
        analysis_type: "profile",
        analysis_year: "2025",
        confidence_score: 85.0,
        content_type: "text",
        critical_issues_count: 0,
        critical_issues_list: "[]",
        data_completeness: 100.0,
        dev_holdings_percent: 0.0,
        doc_id: "analysis_1756935006_4k3Dyjzv",
        doc_type: "token_analysis",
        freeze_authority_active: False,
        has_ai_analysis: False,
        has_goplus: False,
        has_rugcheck: False,
        has_solsniffer: False,
        holder_count: 250721,
        liquidity: 0.0,
        lp_status: "locked",
        market_cap: 0.0,
        mint_authority_active: False,
        overall_score: 60.0,
        price_change_24h: 0.0,
        price_usd: 0.0,
        processing_time: 1.81,
        recommendation: "AVOID",
        risk_level: "low",
        security_score: 100,
        security_status: "safe",
        services_successful: 3,
        sniper_risk: "unknown",
        source_event: "profile_pump",
        timestamp: "2025-09-03T23:30:06.713996",
        timestamp_unix: 1756935006,
        token_address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        token_name: "Unknown Token",
        token_symbol: "N/A",
        total_supply: 0.0,
        volatility_risk: "unknown",
        volume_24h: 0.0,
        volume_liquidity_ratio: 0.0,
        warnings_count: 0,
        warnings_list: "[]",
        whale_control_percent: 0.0,
        whale_count: 0,
        whale_risk: "unknown",
      },
    ],
    documents: [
      "Token: Raydium (RAY). AI-Enhanced deep analysis using llama-3.3-70b-versatile. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 86.7. AI analysis score: 92.0. AI recommendation: BUY. AI insights: Market cap of $931 million suggests growth potential with stable liquidity; Low recent volatility of 0.29% indicates market stability; Top 10 holders control only 0.8% of tokens, indicating a healthy distribution. Price: $3.47024604. Market cap: $1,892,543,833. high trading volume: $7,460,778. excellent liquidity: $36,828,091. Perfect token distribution - no whales. low volatility: 0.29%. Has 1 security warnings. Summary: AI-Enhanced Analysis: 86.7/100 | AI Recommendation: BUY | Risk: LOW | 7 data sources. Analysis reasoning: Comprehensive analysis of market fundamentals, risk metrics, and security assessment indicates a low-risk investment opportunity with strong growth potential, supported by a stable market cap, low vol.... Data from 7 sources. Processing time: 4.86s total (1.50s AI). Analyzed on: 2025-09-03 14:11:37.",
      "Token: Raydium (RAY). Traditional quick analysis. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 83.1. Price: $3.45990774. Market cap: $1,892,543,833. high trading volume: $7,472,328. excellent liquidity: $36,839,032. Perfect token distribution - no whales. low volatility: 0.26%. Has 1 security warnings. Summary: Security verified. Enhanced analysis from 7 sources.. Analysis reasoning: Analysis score: 83.1/100. Security verification passed. Perfect token distribution. Analysis based on 7 data sources..... Data from 7 sources. Processing time: 3.66s. Analyzed on: 2025-09-03 14:12:56.",
      "Token: Raydium (RAY). Traditional quick analysis. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 83.1. Price: $3.43059107. Market cap: $1,898,093,814. high trading volume: $6,844,909. excellent liquidity: $36,580,705. Perfect token distribution - no whales. low volatility: 0.08%. Has 1 security warnings. Summary: Security verified. Enhanced analysis from 7 sources.. Analysis reasoning: Analysis score: 83.1/100. Security verification passed. Perfect token distribution. Analysis based on 7 data sources..... Data from 7 sources. Processing time: 9.88s. Analyzed on: 2025-09-03 22:39:21.",
      "Traditional quick analysis. Security status: UNSAFE: Security verification failed. Risk level: unknown. Recommendation: HOLD. Overall score: 0.0. Perfect token distribution - no whales. Summary: Analysis completed: 0.0/100 score from 0 sources. Analysis reasoning: Analysis score: 0/100. Security concerns identified. Analysis based on 0 data sources..... Data from 0 sources. Processing time: 0.00s. Analyzed on: 2025-09-03 22:40:25.",
      "Traditional quick analysis. Security status: UNSAFE: Security verification failed. Risk level: unknown. Recommendation: HOLD. Overall score: 0.0. Perfect token distribution - no whales. Summary: Analysis completed: 0.0/100 score from 0 sources. Analysis reasoning: Analysis score: 0/100. Security concerns identified. Analysis based on 0 data sources..... Data from 0 sources. Processing time: 0.00s. Analyzed on: 2025-09-03 22:42:23.",
      "Traditional quick analysis. Security status: UNSAFE: Security verification failed. Risk level: unknown. Recommendation: HOLD. Overall score: 0.0. Perfect token distribution - no whales. Summary: Analysis completed: 0.0/100 score from 0 sources. Analysis reasoning: Analysis score: 0/100. Security concerns identified. Analysis based on 0 data sources..... Data from 0 sources. Processing time: 0.00s. Analyzed on: 2025-09-03 22:44:12.",
      "Token: Raydium (RAY). Traditional quick analysis. Security status: SECURE with 1 warning. Risk level: low. Recommendation: consider. Overall score: 83.1. Price: $3.42928325. Market cap: $1,898,093,814. high trading volume: $6,858,517. excellent liquidity: $36,580,705. Perfect token distribution - no whales. low volatility: 0.23%. Has 1 security warnings. Summary: Security verified. Enhanced analysis from 7 sources.. Analysis reasoning: Analysis score: 83.1/100. Security verification passed. Perfect token distribution. Analysis based on 7 data sources..... Data from 7 sources. Processing time: 5.41s. Analyzed on: 2025-09-03 23:00:19.",
      "Traditional quick analysis. Security status: UNSAFE: Security verification failed. Risk level: unknown. Recommendation: HOLD. Overall score: 0.0. Perfect token distribution - no whales. Summary: Analysis completed: 0.0/100 score from 0 sources. Analysis reasoning: Analysis score: 0/100. Security concerns identified. Analysis based on 0 data sources..... Data from 0 sources. Processing time: 0.00s. Analyzed on: 2025-09-03 23:09:48.",
      "Traditional profile analysis. Security status: SECURE: All security checks passed. Risk level: low. Recommendation: AVOID. Overall score: 60.0. Perfect token distribution - no whales. Summary: Pump Detection analysis completed with 60.0% score. Analysis reasoning: Pump profile analysis completed with specialized focus.... Data from 4 sources. Processing time: 1.81s total (1.00s AI). Analyzed on: 2025-09-03 23:30:06.",
    ],
    uris: None,
    data: None,
  },
];
